version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm ci

  build:
    commands:
      - npm run build
